#!/usr/bin/env bash
# Copyright 2026 YugabyteDB, Inc.
# SPDX-License-Identifier: MPL-2.0
#
# clean-stand.sh [--delete] — remove what acceptance tests left on the
# standing fixtures. A test killed mid-run (Ctrl-C, go test timeout, cancelled
# job) never reaches its destroy step; what it created stays until someone
# deletes it, and a leaked universe keeps its VMs and public IPs.
#
# Everything with a test name is in scope (acc-*, plus tf-acctest-* storage
# configs from the tests that still use that prefix):
#   - on each fixture YBA (GCP through the IAP tunnel, AWS, Azure): universes
#     (force delete), telemetry providers, cloud providers (YBA deletes their
#     hooks with them), certificates, storage configs, KMS configs, hooks and
#     users;
#   - what the load balancer and OS-upgrade tests create in the clouds
#     directly: GCP forwarding rules, backend services, health checks,
#     instances, disks and addresses in TF_VAR_GCP_REGION; Azure load
#     balancers in TF_VAR_AZURE_RG; AWS ybalb-* load balancers in the fixture
#     VPC.
#
# Without --delete it only prints the plan. With --delete it prints the plan,
# asks for confirmation, then deletes exactly what it printed. Names are the
# only filter, with no age check: run it only when no acceptance run is in
# progress on any branch, or it deletes that run's resources too.
#
# Needs acctest/env (make -C acctest env) and the az login from
# make -C acctest auth. aws uses the env's keys; gcloud uses the fixture
# service account when this script opens the tunnel, else your login.
set -euo pipefail

cd "$(dirname "$0")"

mode=plan
case "${1:-}" in
"") ;;
--delete) mode=delete ;;
*)
	echo "usage: $0 [--delete]" >&2
	exit 2
	;;
esac

# The GCP YBA is reachable only through the tunnel, so run again inside it.
if [ -z "${CLEAN_STAND_IN_TUNNEL:-}" ]; then
	if [ ! -f env ]; then
		echo "clean-stand: acctest/env not found - run: make -C acctest env" >&2
		exit 1
	fi
	set -a
	# shellcheck disable=SC1091 # generated by make -C acctest env, gitignored
	. ./env
	set +a
	CLEAN_STAND_IN_TUNNEL=1 exec ./with-yba-tunnel.sh "./$(basename "$0")" "$@"
fi

# AWS region of the load balancer test (awsLBConfig).
AWS_LB_REGION=us-west-2

# YBA collections in delete order: universes first, so nothing below is still
# in use. Each jq program selects test objects as [uuid, name].
YBA_KINDS='universes	.[] | select(.name | test("^acc-")) | [.universeUUID, .name]
telemetry_provider	.[] | select(.name | test("^acc-")) | [.uuid, .name]
providers	.[] | select(.name | test("^acc-")) | [.uuid, .name]
certificates	.[] | select(.label | test("^acc-")) | [.uuid, .label]
configs	.[] | select(.type == "STORAGE" and (.configName | test("^(acc|tf-acctest)-"))) | [.configUUID, .configName]
kms_configs	.[] | .metadata | select(.name | test("^acc-")) | [.configUUID, .name]
hooks	.[] | select(.name | test("^acc-")) | [.uuid, .name]
users	.[] | select(.email | test("^acc-")) | [.uuid, .email]'

# GCP kinds in delete order, with the list scope flag for each.
GCP_KINDS='forwarding-rules regional
backend-services regional
health-checks regional
instances zonal
disks zonal
addresses regional'

failed=0
plan=$(mktemp)
trap 'rm -f "$plan"' EXIT

# add TARGET KIND ID NAME [LOCATION] appends one object to the plan.
add() { printf '%s\t%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" "${5:-}" >>"$plan"; }

# planned TARGET KIND prints "ID<tab>NAME<tab>LOCATION" for each planned object.
planned() {
	awk -F'\t' -v t="$1" -v k="$2" '$1 == t && $2 == k { print $3 "\t" $4 "\t" $5 }' "$plan"
}

# yba CLOUD METHOD PATH calls that cloud's fixture YBA and prints the body. An
# HTTP error fails with YBA's message. The token reaches curl on stdin, not argv.
yba() {
	local hv="TF_VAR_$1_YBA_HOST" kv="TF_VAR_$1_YBA_API_KEY" body code
	body=$(mktemp)
	code=$(printf 'header = "X-AUTH-YW-API-TOKEN: %s"\n' "${!kv}" |
		curl -sSk --max-time 120 -K - -o "$body" -w '%{http_code}' \
			-X "$2" "https://${!hv}/api/v1/$3") || {
		rm -f "$body"
		return 1
	}
	if [ "$code" -ge 400 ]; then
		echo "clean-stand: $1 YBA: $2 $3: HTTP $code: $(cat "$body")" >&2
		rm -f "$body"
		return 1
	fi
	cat "$body"
	rm -f "$body"
}

customer() { yba "$1" GET customers | jq -r '.[0].uuid'; }

# wait_task CLOUD CUSTOMER TASK polls a YBA task for up to 30 minutes.
wait_task() {
	local status
	for _ in $(seq 1 180); do
		status=$(yba "$1" GET "customers/$2/tasks/$3" | jq -r .status) || return 1
		case $status in
		Success) return 0 ;;
		Failure | Aborted)
			echo "clean-stand: $1 YBA: task $3 ended $status" >&2
			return 1
			;;
		esac
		sleep 10
	done
	echo "clean-stand: $1 YBA: task $3 still running after 30m" >&2
	return 1
}

has_yba() {
	local hv="TF_VAR_$1_YBA_HOST" kv="TF_VAR_$1_YBA_API_KEY"
	if [ -z "${!hv:-}" ] || [ -z "${!kv:-}" ]; then
		echo "clean-stand: $hv or $kv not set, skipping the $1 YBA" >&2
		return 1
	fi
}

plan_yba() {
	local cloud=$1 cust kind program
	cust=$(customer "$cloud") || return 1
	while IFS=$'\t' read -r kind program; do
		yba "$cloud" GET "customers/$cust/$kind" | jq -r "$program | @tsv" |
			while IFS=$'\t' read -r id name; do
				add "$cloud" "$kind" "$id" "$name"
			done || return 1
	done <<<"$YBA_KINDS"
}

plan_gcp() {
	local project=$TF_VAR_GCP_PROJECT_ID region=$TF_VAR_GCP_REGION kind scope
	while read -r kind scope; do
		if [ "$scope" = regional ]; then
			gcloud compute "$kind" list --project="$project" --regions="$region" \
				--filter='name ~ ^acc-' --format='value(name,region.basename())'
		else
			gcloud compute "$kind" list --project="$project" \
				--filter="name ~ ^acc- AND zone ~ /zones/$region-" \
				--format='value(name,zone.basename())'
		fi | while IFS=$'\t' read -r name location; do
			add gcp "$kind" "$name" "$name" "$location"
		done || return 1
	done <<<"$GCP_KINDS"
}

plan_azure() {
	az network lb list --subscription "$TF_VAR_AZURE_SUBSCRIPTION_ID" \
		--resource-group "$TF_VAR_AZURE_RG" \
		--query "[?starts_with(name, 'acc-')].[id, name]" --output tsv |
		while IFS=$'\t' read -r id name; do
			add azure lb "$id" "$name" "$TF_VAR_AZURE_RG"
		done
}

plan_aws() {
	aws elbv2 describe-load-balancers --region "$AWS_LB_REGION" \
		--query "LoadBalancers[?starts_with(LoadBalancerName, 'ybalb-') && VpcId == '$TF_VAR_AWS_VPC_ID'].[LoadBalancerArn, LoadBalancerName]" \
		--output text |
		while IFS=$'\t' read -r arn name; do
			add aws lb "$arn" "$name" "$AWS_LB_REGION"
		done
}

# delete_yba CLOUD dispatches each kind's deletes, then waits for their tasks
# before moving to the next kind.
delete_yba() {
	local cloud=$1 cust kind id name query resp task tasks
	cust=$(customer "$cloud") || return 1
	while IFS=$'\t' read -r kind _; do
		tasks=
		while IFS=$'\t' read -r id name _; do
			echo "deleting $cloud YBA $kind $name"
			query=
			[ "$kind" != universes ] || query='?isForceDelete=true'
			resp=$(yba "$cloud" DELETE "customers/$cust/$kind/$id$query") || {
				failed=1
				continue
			}
			task=$(jq -r '.taskUUID // empty' <<<"$resp" 2>/dev/null || true)
			tasks="$tasks $task"
		done < <(planned "$cloud" "$kind")
		for task in $tasks; do
			wait_task "$cloud" "$cust" "$task" || failed=1
		done
	done <<<"$YBA_KINDS"
}

delete_gcp() {
	local kind scope name location where
	while read -r kind scope; do
		while IFS=$'\t' read -r name _ location; do
			echo "deleting gcp $kind $name"
			where=--zone=$location
			[ "$scope" != regional ] || where=--region=$location
			gcloud compute "$kind" delete "$name" --project="$TF_VAR_GCP_PROJECT_ID" \
				"$where" --quiet || failed=1
		done < <(planned gcp "$kind")
	done <<<"$GCP_KINDS"
}

delete_azure() {
	local id name
	while IFS=$'\t' read -r id name _; do
		echo "deleting azure lb $name"
		az network lb delete --ids "$id" || failed=1
	done < <(planned azure lb)
}

delete_aws() {
	local arn name
	while IFS=$'\t' read -r arn name _; do
		echo "deleting aws lb $name"
		aws elbv2 delete-load-balancer --region "$AWS_LB_REGION" \
			--load-balancer-arn "$arn" || failed=1
	done < <(planned aws lb)
}

for cloud in GCP AWS AZURE; do
	if has_yba "$cloud"; then
		plan_yba "$cloud" || {
			echo "clean-stand: could not list the $cloud YBA" >&2
			failed=1
		}
	fi
done
plan_gcp || {
	echo "clean-stand: could not list GCP resources" >&2
	failed=1
}
plan_azure || {
	echo "clean-stand: could not list Azure load balancers" >&2
	failed=1
}
plan_aws || {
	echo "clean-stand: could not list AWS load balancers" >&2
	failed=1
}

if [ ! -s "$plan" ]; then
	echo "Nothing to clean."
	exit "$failed"
fi
echo "Test objects on the stand:"
awk -F'\t' '{ printf "  %-6s %-18s %s\n", $1, $2, $4 }' "$plan"

if [ "$mode" = plan ]; then
	echo "Nothing deleted. Run again with --delete to delete the objects above."
	exit "$failed"
fi
if [ "$failed" -ne 0 ]; then
	echo "clean-stand: the plan is incomplete (see the errors above); not deleting" >&2
	exit 1
fi
printf 'Delete the %s objects above? Type "delete" to continue: ' "$(wc -l <"$plan" | tr -d ' ')"
read -r answer
if [ "$answer" != delete ]; then
	echo "Nothing deleted."
	exit 1
fi

for cloud in GCP AWS AZURE; do
	if has_yba "$cloud" 2>/dev/null; then
		delete_yba "$cloud" || failed=1
	fi
done
delete_gcp
delete_azure
delete_aws
exit "$failed"
