// Licensed to YugabyteDB, Inc. under one or more contributor license
// agreements. See the NOTICE file distributed with this work for
// additional information regarding copyright ownership. Yugabyte
// licenses this file to you under the Mozilla License, Version 2.0
// (the "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
// http://mozilla.org/MPL/2.0/.
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package providerutil

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

// CommonProviderSchema returns schema fields common to all cloud providers
func CommonProviderSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"name": {
			Type:        schema.TypeString,
			Required:    true,
			Description: "Name of the provider.",
		},
		"version": {
			Type:        schema.TypeInt,
			Computed:    true,
			Description: "Provider version. Read-only, incremented on each update.",
		},
		"air_gap_install": {
			Type:     schema.TypeBool,
			Optional: true,
			Default:  false,
			Description: "Flag indicating if YugabyteDB nodes are installed in an air-gapped " +
				"environment, lacking access to the public internet for package downloads. " +
				"Default is false.",
		},
		"ntp_servers": {
			Type:     schema.TypeList,
			Optional: true,
			Computed: true,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "List of NTP servers for time synchronization.",
		},
		"set_up_chrony": {
			Type:     schema.TypeBool,
			Optional: true,
			Default:  false,
			Description: "Set up NTP chrony service. When true with empty ntp_servers, " +
				"uses cloud provider's NTP server (e.g., AWS Time Sync). " +
				"When true with ntp_servers specified, uses custom NTP servers. " +
				"When false, assumes NTP is pre-configured in the machine image. " +
				"Default is false.",
		},
		"access_key_code": {
			Type:        schema.TypeString,
			Computed:    true,
			Description: "Access key code for this provider. Read-only, generated by YBA.",
		},
	}
}

// ImageBundleSchema returns schema for image bundles
// Matches yba-cli image bundle structure
func ImageBundleSchema() *schema.Schema {
	return &schema.Schema{
		Description: "Custom image bundles for the provider. " +
			"At least one image_bundles or yba_managed_image_bundles block must be specified.",
		Type:     schema.TypeList,
		Optional: true,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"uuid": {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Image bundle UUID.",
				},
				"name": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Name of the image bundle.",
				},
				"use_as_default": {
					Type:     schema.TypeBool,
					Optional: true,
					Default:  false,
					Description: "Flag indicating if the image bundle should be " +
						"used as default for this architecture.",
				},
				"details": {
					Type:     schema.TypeList,
					Required: true,
					MaxItems: 1,
					Elem: &schema.Resource{
						Schema: map[string]*schema.Schema{
							"ssh_user": {
								Type:        schema.TypeString,
								Required:    true,
								Description: "SSH user for the image.",
							},
							"ssh_port": {
								Type:        schema.TypeInt,
								Optional:    true,
								Computed:    true,
								Description: "SSH port for the image. Default is 22.",
							},
							"global_yb_image": {
								Type:        schema.TypeString,
								Optional:    true,
								Computed:    true,
								Description: "Global YB image for the bundle.",
							},
						},
					},
					Description: "Image bundle details including SSH configuration. " +
						"Architecture is always x86_64 for this cloud provider.",
				},
			},
		},
	}
}

// YBADefaultImageBundleSchema returns schema for YBA managed image bundles for AWS.
// AWS supports both x86_64 and aarch64 architectures (up to two entries).
// At least one of image_bundles or yba_managed_image_bundles must be specified.
// Omitting this block entirely removes Terraform's tracking of YBA-managed bundles
// and causes any previously tracked ones to be removed from the provider on the
// next apply.
func YBADefaultImageBundleSchema() *schema.Schema {
	return &schema.Schema{
		Description: "YBA managed image bundles for the provider. " +
			"At least one image_bundles or yba_managed_image_bundles block must be specified. " +
			"AWS supports up to two entries: one for x86_64 and one for aarch64. " +
			"Omit this block to stop managing YBA default images via Terraform " +
			"(any previously tracked bundles will be removed from the provider on the next apply).",
		Type:     schema.TypeList,
		Optional: true,
		MaxItems: 2,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"uuid": {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Image bundle UUID.",
				},
				"name": {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Image bundle name assigned by YBA.",
				},
				"arch": {
					Type:         schema.TypeString,
					Required:     true,
					Description:  "Image bundle architecture. Allowed values: x86_64, aarch64.",
					ValidateFunc: validation.StringInSlice([]string{"x86_64", "aarch64"}, false),
				},
				"use_as_default": {
					Type:     schema.TypeBool,
					Optional: true,
					Default:  false,
					Description: "Flag indicating if the image bundle should be " +
						"used as default for this architecture.",
				},
			},
		},
	}
}

// YBADefaultImageBundleSchemaX86Only returns schema for YBA managed image bundles
// for GCP and Azure. Only x86_64 is supported. At least one of image_bundles or
// yba_managed_image_bundles must be specified. Omitting removes previously tracked
// YBA-managed bundles from the provider on the next apply.
func YBADefaultImageBundleSchemaX86Only() *schema.Schema {
	return &schema.Schema{
		Description: "YBA managed image bundles for the provider. " +
			"At least one image_bundles or yba_managed_image_bundles block must be specified. " +
			"Only x86_64 architecture is supported. " +
			"Omit this block to stop managing YBA default images via Terraform " +
			"(any previously tracked bundles will be removed from the provider on the next apply).",
		Type:     schema.TypeList,
		Optional: true,
		MaxItems: 1,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"uuid": {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Image bundle UUID.",
				},
				"name": {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Image bundle name assigned by YBA.",
				},
				"arch": {
					Type:         schema.TypeString,
					Required:     true,
					Description:  "Image bundle architecture. Only x86_64 is supported for this cloud provider.",
					ValidateFunc: validation.StringInSlice([]string{"x86_64"}, false),
				},
				"use_as_default": {
					Type:     schema.TypeBool,
					Optional: true,
					Default:  false,
					Description: "Flag indicating if the image bundle should be " +
						"used as default.",
				},
			},
		},
	}
}

// RegionsSchema returns schema for cloud provider regions
// Common schema used by AWS, GCP, Azure providers
func RegionsSchema() *schema.Schema {
	return &schema.Schema{
		Description: "Regions associated with cloud provider.",
		Type:        schema.TypeList,
		Required:    true,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"uuid": {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Region UUID.",
				},
				"code": {
					Type:        schema.TypeString,
					Optional:    true,
					Computed:    true,
					Description: "Region code. Varies by cloud provider.",
				},
				"name": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Name of the region.",
				},
				"latitude": {
					Type:        schema.TypeFloat,
					Optional:    true,
					Computed:    true,
					Description: "Latitude of the region.",
				},
				"longitude": {
					Type:        schema.TypeFloat,
					Optional:    true,
					Computed:    true,
					Description: "Longitude of the region.",
				},
				"security_group_id": {
					Type:     schema.TypeString,
					Optional: true,
					Description: "Security group ID for this region. " +
						"Only applicable for AWS/Azure providers.",
				},
				"vnet_name": {
					Type:     schema.TypeString,
					Optional: true,
					Description: "VPC/VNet name for this region. " +
						"Only applicable for AWS/Azure/GCP providers.",
				},
				"instance_template": {
					Type:     schema.TypeString,
					Optional: true,
					Description: "Instance template for this region. " +
						"Only applicable for GCP provider.",
				},
				"zones": ZonesSchema(),
			},
		},
	}
}

// ZonesSchema returns schema for availability zones
func ZonesSchema() *schema.Schema {
	return &schema.Schema{
		Type:     schema.TypeList,
		Optional: true,
		Computed: true,
		Description: "Zones (availability zones) associated with the region. " +
			"YBA may auto-discover additional zones in the region.",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"uuid": {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Zone UUID.",
				},
				"code": {
					Type:        schema.TypeString,
					Optional:    true,
					Computed:    true,
					Description: "Zone code.",
				},
				"name": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Name of the zone.",
				},
				"subnet": {
					Type:        schema.TypeString,
					Optional:    true,
					Description: "Subnet ID for this zone.",
				},
				"secondary_subnet": {
					Type:        schema.TypeString,
					Optional:    true,
					Description: "Secondary subnet ID for this zone.",
				},
			},
		},
	}
}

// AccessKeySchema returns schema for SSH access keys
func AccessKeySchema() *schema.Schema {
	return &schema.Schema{
		Type:        schema.TypeList,
		Optional:    true,
		MaxItems:    1,
		Description: "SSH access key configuration for the provider.",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"key_pair_name": {
					Type:        schema.TypeString,
					Optional:    true,
					Description: "Name of the SSH key pair.",
				},
				"ssh_private_key_content": {
					Type:        schema.TypeString,
					Optional:    true,
					Sensitive:   true,
					Description: "Content of the SSH private key.",
				},
				"skip_key_validation": {
					Type:     schema.TypeBool,
					Optional: true,
					Default:  false,
					Description: "Skip SSH key pair validation and upload. " +
						"Default is false.",
				},
			},
		},
	}
}
